# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_personalisation', '0014_add_frozen_to_segment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='sessions',
        ),
        migrations.AddField(
            model_name='segment',
            name='session_keys',
            field=models.TextField(default=''),
        ),
    ]
